# Database connection
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Pial@2023
    url: jdbc:mysql://mysql_db_c:3306/inventory_demo?createDatabaseIfNotExist=true

  # Redis
  data:
    redis:
      host: redis-stack-c
      port: 6379
      password: Pial@2023

  # RabbitMQ
  rabbitmq:
    host: rabbitmq
    port: 5672

# Elasticsearch
app:
  elasticsearch:
    host: elasticsearch_c
    port: 9200